# Generated by Django 4.2.1 on 2023-05-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseryapp', '0002_alter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=509),
        ),
    ]
