# Generated by Django 4.2.1 on 2023-05-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseryapp', '0008_productcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='qunatity',
            field=models.IntegerField(default=1),
        ),
    ]
